#include <stdio.h>
#include <stdbool.h> 
#include <stdlib.h> 
#include <string.h> 
#include <ncurses.h> 
#include <unistd.h> 
#include <SDL2/SDL.h> 
#include "locations.c"
#include "items.c"
#include "declarations.c"
#include "functions.c"
#include "actions.c"
#include "render.c"
